### ISSUE TITLE
遇到kotlin.KotlinNullPointerException的异常，请问有没有解决方案了

### ISSUE THREAD

**Issue by WindySha** [Blankeer/WechatBotXposed#13]
具体报错日志：
```
04-26 15:33:24.883 11775-11803/? E/Xposed: kotlin.KotlinNullPointerException
        at com.blanke.wechatbotxposed.hook.Classes$ChattingFooterEventImpl$2.invoke(Classes.kt:13)
        at com.blanke.wechatbotxposed.hook.Classes$ChattingFooterEventImpl$2.invoke(Classes.kt:10)
        at com.gh0u1l5.wechatmagician.spellbook.WechatGlobal$wxLazy$2.invoke(WechatGlobal.kt:72)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
        at com.blanke.wechatbotxposed.hook.Classes.getChattingFooterEventImpl(Classes.kt)
        at com.blanke.wechatbotxposed.hook.SendMsgHooker$chattingFooterEventImplHook$1.invoke(SendMsgHooker.kt:50)
        at com.blanke.wechatbotxposed.hook.SendMsgHooker$chattingFooterEventImplHook$1.invoke(SendMsgHooker.kt:8)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1$1.invoke(XposedUtil.kt:50)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1$1.invoke(XposedUtil.kt:14)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$tryHook$2.invoke(XposedUtil.kt:35)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$tryHook$2.invoke(XposedUtil.kt:14)
        at com.gh0u1l5.wechatmagician.spellbook.util.BasicUtil$tryAsynchronously$1.invoke(BasicUtil.kt:33)
        at com.gh0u1l5.wechatmagician.spellbook.util.BasicUtil$tryAsynchronously$1.invoke(BasicUtil.kt:9)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
```
Andorid 6.0
Root环境
Nexsus手机
微信7.0.0版本

**Comment by SES-xuelan** [comment]
我也遇到了，Android 5.1,ROOT 模拟器
