### ISSUE TITLE
#报错，kotlin.KotlinNullPointerException，无法运行#

### ISSUE THREAD

**Issue by originlan** [Blankeer/WechatBotXposed#2]
重新导库可修复，没有查明原因，另外SpellBook已经更新到0.05了， SpellBook.startup方法参数有变，请问做适配吗

**Comment by Blankeer** [comment]
你是什么环境？
xposed or VirtualXposed?
模拟器还是真机？
微信版本？

**Comment by originlan** [comment]
Android7.0
Xposed
小米mix2
微信6.6.6

**Comment by originlan** [comment]
报错的地方貌似和你的代码没关系，是spellbook初始化hook‘wx‘的时候报空，目前解决办法删掉重装，重启就正常了
`05-16 17:09:12.387 E/Xposed  ( 3398): kotlin.KotlinNullPointerException
05-16 17:09:12.387 E/Xposed  ( 3398): 	at com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.ui.Classes$MMBaseAdapter$2.invoke(Classes.kt:25)
05-16 17:09:12.387 E/Xposed  ( 3398): 	at com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.ui.Classes$MMBaseAdapter$2.invoke(Classes.kt:11)
05-16 17:09:12.387 E/Xposed  ( 3398): 	at com.gh0u1l5.wechatmagician.spellbook.WechatGlobal$wxLazy$2.invoke(WechatGlobal.kt:72)
05-16 17:09:12.387 E/Xposed  ( 3398): 	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
05-16 17:09:12.387 E/Xposed  ( 3398): 	at com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.ui.Classes.getMMBaseAdapter(Classes.kt)
05-16 17:09:12.387 E/Xposed  ( 3398): 	at com.gh0u1l5.wechatmagician.spellbook.hookers.ListViewHider$MMBaseAdapterHooker$1.invoke(ListViewHider.kt:86)
05-16 17:09:12.387 E/Xposed  ( 3398): 	at com.gh0u1l5.wechatmagician.spellbook.hookers.ListViewHider$MMBaseAdapterHooker$1.invoke(ListViewHider.kt:17)
05-16 17:09:12.387 E/Xposed  ( 3398): 	at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1$1.invoke(XposedUtil.kt:50)
05-16 17:09:12.387 E/Xposed  ( 3398): 	at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1$1.invoke(XposedUtil.kt:14)
05-16 17:09:12.387 E/Xposed  ( 3398): 	at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$tryHook$1.invoke(XposedUtil.kt:34)
05-16 17:09:12.387 E/Xposed  ( 3398): 	at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$tryHook$1.invoke(XposedUtil.kt:14)
05-16 17:09:12.387 E/Xposed  ( 3398): 	at com.gh0u1l5.wechatmagician.spellbook.util.BasicUtil.tryVerbosely(BasicUtil.kt:21)
05-16 17:09:12.387 E/Xposed  ( 3398): 	at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil.tryHook(XposedUtil.kt:34)
05-16 17:09:12.387 E/Xposed  ( 3398): 	at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil.access$tryHook(XposedUtil.kt:14)
05-16 17:09:12.387 E/Xposed  ( 3398): 	at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1.run(XposedUtil.kt:45)
05-16 17:09:12.387 E/Xposed  ( 3398): 	at android.os.Handler.handleCallback(Handler.java:754)
05-16 17:09:12.387 E/Xposed  ( 3398): 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-16 17:09:12.387 E/Xposed  ( 3398): 	at android.os.Looper.loop(Looper.java:163)
05-16 17:09:12.387 E/Xposed  ( 3398): 	at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by Blankeer** [comment]
我跟 spellbook 的作者说了这个问题，目前还没有回复。
很奇怪，有些环境不行，有些可以。
我用的真机 VirtualXposed + 微信 6.6.6 版本可以正常使用，其他环境好像都有问题。
你可以试试这个环境。
谢谢

**Comment by yongdange** [comment]
我尝试了重新安装也还是出现nullpointer的问题。

**Comment by xfx761** [comment]
> spellbook初始化hook‘wx‘

删除重装，是删除微信吗？还是删除什么

**Comment by lanceli** [comment]
我重装了微信好了 6.6.7

**Comment by lanceli** [comment]
然后重启设备又挂了 KotlinNullPointerException

**Comment by NicholasLiao** [comment]
> 我跟 spellbook 的作者说了这个问题，目前还没有回复。
> 很奇怪，有些环境不行，有些可以。
> 我用的真机 VirtualXposed + 微信 6.6.6 版本可以正常使用，其他环境好像都有问题。
> 你可以试试这个环境。
> 谢谢

请问支持6.7.3吗？我运行报同样的错误
